// <auto-generated />
namespace LeaveManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ReasonAddedInLeaves : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReasonAddedInLeaves));
        
        string IMigrationMetadata.Id
        {
            get { return "202403160759544_Reason Added In Leaves"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
